# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    api_routes.config: '%kernel.project_dir%/config/api_routes/routes.yaml'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Middleware\:
        resource: '../src/Middleware/'
        public: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

    App\EventListener\ExceptionEventListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Service\RouteLoader:
        arguments:
            $configPath: '%api_routes.config%'

    App\Service\Auth\ApiKeyAuthenticator:
        tags:
            - { name: app.authenticator }

    App\Service\Auth\BasicAuthenticator:
        tags:
            - { name: app.authenticator }

    App\Service\AuthenticationManager:
        arguments:
            $authenticators: !tagged_iterator 'app.authenticator'

    App\Service\Logging\Strategy\FileLogStrategy:
        tags:
            - { name: app.log.strategy }

    App\Service\Logging\Strategy\StreamLogStrategy:
        tags:
            - { name: app.log.strategy }

    App\Service\Logging\Strategy\SyslogLogStrategy:
        tags:
            - { name: app.log.strategy }

    App\Service\Logging\LoggingService:
        arguments:
            $strategies: !tagged_iterator 'app.log.strategy'
